import Link from 'next/link';
import { ResponsibleUseBanner } from '@/components/ResponsibleUseModal';

export default function ResponsibleUsePage() {
  return (
    <div className="space-y-8 max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
      <div className="space-y-2 text-center">
        <h1 className="text-4xl font-bold">Responsible Use</h1>
        <p className="text-lg text-muted-foreground">
          Our commitment to ethical AI and academic integrity.
        </p>
      </div>

      <ResponsibleUseBanner />

      <div className="bg-card border rounded-lg p-6 space-y-6">
        <section>
          <h2 className="text-2xl font-semibold mb-2">Our Philosophy</h2>
          <p className="text-muted-foreground">
            At Integrity AI, we believe that AI should be a partner in the creative process, not a substitute for human effort. Our tools are designed to assist you in refining your ideas and expressing them with greater clarity, style, and impact.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-2">Academic and Professional Integrity</h2>
          <p className="text-muted-foreground mb-4">
            The use of AI writing assistants, including Integrity AI, comes with a responsibility. We urge all users to adhere to the following principles:
          </p>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground">
            <li>**Always cite your sources.**</li>
            <li>**Ensure the final work is your own.**</li>
            <li>**Review and edit the output to ensure it reflects your original voice and intent.**</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-2">Ethical Use Cases</h2>
          <ul className="list-disc list-inside space-y-2 text-muted-foreground">
            <li>Improving the clarity and flow of your original writing.</li>
            <li>Rewriting drafts to match a specific tone or audience.</li>
            <li>Translating text to a different language.</li>
            <li>Checking your work for grammar and plagiarism before submission.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-2">Forbidden Use Cases</h2>
          <p className="text-muted-foreground">
            Using Integrity AI to deceive or misrepresent authorship is strictly against our terms of service. This includes, but is not limited to:
          </p>
          <ul className="list-disc list-inside space-y-2 text-red-500">
            <li>Submitting work entirely generated by AI as your own without significant modification.</li>
            <li>Using the humanizer to bypass AI detection systems in academic or professional settings.</li>
            <li>Generating content for malicious purposes, such as creating misinformation.</li>
          </ul>
        </section>
      </div>
      
      <div className="text-center">
        <Link
          href="/login"
          className="px-6 py-3 font-semibold rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
        >
          I Understand & Accept
        </Link>
      </div>
    </div>
  );
}
